[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet be-nexus-fs.dll"
healthcheckPath = "/weatherforecast"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Deploy only on these branches
[environments]
production.watch = ["main"]
development.watch = ["dev"]

# Disable PR deployments
[deploy.pr]
enabled = false
