using Infrastructure.Configuration;
using Infrastructure.Services.Security;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text.Json;

namespace Infrastructure.Services.Security
{
    /// <summary>
    /// Strategy Pattern implementation for Clerk authentication.
    /// Handles JWT token validation using Clerk's JWKS endpoint.
    /// </summary>
    public class ClerkAuthStrategy : IAuthStrategy
    {
        private readonly ClerkOptions _clerkOptions;
        private readonly JwtSecurityTokenHandler _tokenHandler;

        public string StrategyName => "Clerk";

        public ClerkAuthStrategy(IOptions<ClerkOptions> clerkOptions)
        {
            _clerkOptions = clerkOptions.Value;
            _tokenHandler = new JwtSecurityTokenHandler();
        }

        /// <summary>
        /// Authenticates using Clerk JWT token
        /// </summary>
        /// <param name="credentials">Dictionary containing "token" key with JWT token</param>
        /// <returns>True if token is valid, false otherwise</returns>
        public async Task<bool> AuthenticateAsync(Dictionary<string, string> credentials)
        {
            if (!credentials.TryGetValue("token", out var token))
                return false;

            return await ValidateTokenAsync(token);
        }

        /// <summary>
        /// Validates a Clerk JWT token
        /// </summary>
        /// <param name="token">The JWT token to validate</param>
        /// <returns>True if token is valid, false otherwise</returns>
        public async Task<bool> ValidateTokenAsync(string token)
        {
            try
            {
                if (string.IsNullOrEmpty(token))
                    return false;

                // Get the JWKS from Clerk
                var jwks = await GetJwksAsync();
                if (jwks == null)
                    return false;

                var tokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidIssuer = _clerkOptions.Issuer,
                    ValidateAudience = !string.IsNullOrEmpty(_clerkOptions.Audience),
                    ValidAudience = _clerkOptions.Audience,
                    ValidateLifetime = true,
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKeys = jwks.Keys,
                    ClockSkew = TimeSpan.FromMinutes(5)
                };

                var principal = _tokenHandler.ValidateToken(token, tokenValidationParameters, out _);
                return principal != null;
            }
            catch (Exception)
            {
                return false;
            }
        }

        /// <summary>
        /// Generates a token - not applicable for Clerk as tokens are generated by Clerk
        /// </summary>
        /// <param name="credentials">User credentials</param>
        /// <returns>Throws NotSupportedException</returns>
        public Task<string> GenerateTokenAsync(Dictionary<string, string> credentials)
        {
            throw new NotSupportedException("Token generation is handled by Clerk, not the backend service");
        }

        /// <summary>
        /// Revokes a token - handled by Clerk
        /// </summary>
        /// <param name="token">Token to revoke</param>
        /// <returns>Completed task</returns>
        public Task RevokeTokenAsync(string token)
        {
            // Token revocation is handled by Clerk on the frontend
            // We don't need to do anything here
            return Task.CompletedTask;
        }

        /// <summary>
        /// Extracts user claims from a validated JWT token
        /// </summary>
        /// <param name="token">The JWT token</param>
        /// <returns>ClaimsPrincipal with user claims</returns>
        public ClaimsPrincipal? GetUserClaims(string token)
        {
            try
            {
                var jsonToken = _tokenHandler.ReadJwtToken(token);
                var claims = jsonToken.Claims.ToList();
                
                // Add standard claims mapping
                var identity = new ClaimsIdentity(claims, "Clerk");
                return new ClaimsPrincipal(identity);
            }
            catch
            {
                return null;
            }
        }

        /// <summary>
        /// Gets the user ID from the JWT token
        /// </summary>
        /// <param name="token">The JWT token</param>
        /// <returns>User ID or null if not found</returns>
        public string? GetUserId(string token)
        {
            var claims = GetUserClaims(token);
            return claims?.FindFirst("sub")?.Value;
        }

        private async Task<JsonWebKeySet?> GetJwksAsync()
        {
            try
            {
                using var httpClient = new HttpClient();
                var jwksResponse = await httpClient.GetStringAsync(_clerkOptions.JwksUrl);
                return new JsonWebKeySet(jwksResponse);
            }
            catch
            {
                return null;
            }
        }
    }
}