name: Deploy to Dev

on:
  push:
    branches: [dev]

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  deploy-dev:
    runs-on: ubuntu-latest
    needs: tests
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Railway CLI
        run: npm i -g @railway/cli

      - name: Link to Railway Project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}
        run: |
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Deploy to Railway Dev
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}
        run: |
          railway up --service be-nexus-fs --detach
          echo "✅ Deployed to Railway Dev!"
