name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  deploy-prod:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway Production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
        run: |
          railway up --service be-nexus-fs --environment production --ci

      - name: Run EF Core Migrations
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
          CONNECTION_STRING: ${{ secrets.DATABASE_URL }}
        run: |
          cd be-nexus-fs
          dotnet ef database update --connection "$CONNECTION_STRING"
