name: Deploy to Dev

on:
  push:
    branches: [dev]

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  deploy-dev:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Railway
        run: npm i -g @railway/cli
      
      - name: Deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}
        run: railway up --detach
