name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const regex = /NEXUS-\d+/;
            
            if (!regex.test(prTitle)) {
              core.setFailed(
                `PR title must contain a NEXUS ticket reference (e.g., NEXUS-123).\n` +
                `Current title: "${prTitle}"`
              );
            } else {
              core.info(`PR title is valid: "${prTitle}"`);
            }